# Generated by Django 3.0.4 on 2020-03-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_cbv', '0003_auto_20200317_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitebookmark',
            name='pages',
        ),
        migrations.AddField(
            model_name='sitebookmark',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitebookmark',
            name='name',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='sitebookmark',
            name='url',
            field=models.CharField(max_length=4000),
        ),
    ]
