# Generated by Django 3.0.4 on 2020-03-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_cbv', '0004_auto_20200317_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebookmark',
            name='starred',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
