# Generated by Django 3.0.4 on 2020-03-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_cbv', '0005_sitebookmark_starred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitebookmark',
            name='name',
        ),
        migrations.AlterField(
            model_name='sitebookmark',
            name='url',
            field=models.URLField(),
        ),
    ]
