# Generated by Django 3.0.4 on 2020-03-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_cbv', '0006_auto_20200318_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebookmark',
            name='name',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
    ]
