# Generated by Django 3.0.4 on 2020-03-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_cbv', '0007_sitebookmark_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='sitebookmark',
            name='tags',
            field=models.ManyToManyField(blank=True, to='books_cbv.Tag'),
        ),
    ]
