# Generated by Django 3.0.4 on 2020-03-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_cbv', '0008_auto_20200318_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
